### ISSUE TITLE
Profiler.BeginBlock(String) not mapped

### ISSUE THREAD

**Issue by dertom95** [elix22/Urho.Net#4]
Is it possible to make Profiler.BeginBlock(char* name) available in Profiler.cs?
Actually everything but BeginBlock [from the API](https://urho3d.github.io/documentation/HEAD/class_urho3_d_1_1_profiler.html) is mapped. 

Thanks.... urho.net is really fun to use.

**Comment by elix22** [comment]
Yes , I will add it
Stay tuned

**Comment by elix22** [comment]
Added binding Profiler.BeginBlock(String);
I verified it only on Mac , but it should work on all platforms.
Check latest master branch

Every time you update Urho.Net  , you have to 
1 -  clean build your project 
2 -  Restart VS-Code (otherwise IntelliSense won't work)

**Comment by dertom95** [comment]
Thanks, works like a charme.
